language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
before_script:
  - git config --global user.email "will@pedalwrencher.com"
  - git config --global user.name "will"
script:
  - nosetests --with-coverage
after_success:
  - coveralls