language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# setup git
before_script:
  - git config --global user.email "will@pedalwrencher.com"
  - git config --global user.name "will"
# command to run tests
script: nosetests
after_success: coveralls